# Development Stage
FROM node as development

WORKDIR /app

# Copy only package.json and package-lock.json to optimize caching
COPY package.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Copy the rest of the application code
COPY . .

# Application entry point for development
CMD ["npm","run", "start"]
